### ISSUE TITLE
Tiny UI on hdp devices!

### ISSUE THREAD

**Issue by callmehanu** [nylas/nylas-perftools#13]
![shot_160505_152344hide](https://cloud.githubusercontent.com/assets/13230502/15435605/ed7e1cd0-1e82-11e6-87cd-4f599809196b.jpg)

**Comment by callmehanu** [comment]
This happens over Windows 10 and It is really annoying!

**Comment by grinich** [comment]
@haniuman please create this issue at https://github.com/nylas/n1/issues/new
