### ISSUE TITLE
[Question] Loading py2devtools.py json into chrome developer tools timeline

### ISSUE THREAD

**Issue by smetj** [nylas/nylas-perftools#7]
Hi,

Loading the JSON performance data produced by py2devtools.py into Chrome developer tools timeline isn't working for me.

Right click timeline, "Load Timeline data" and load JSON created by py2devtools.py results into nothing.

The error I'm getting:

```
[4763:4763:1230/195530:ERROR:CONSOLE(417)] "TracingStartedInPage event not found.", source: chrome-devtools://devtools/bundled/timeline_module.js (417)
```

Perhaps I'm overlooking something? Any ideas?

**Comment by hyunchel** [comment]
I think by the `timeline` they meant `chart` option from `Profiles` tab.
I was able to get the timeline chart by loading the file into `Profiles` tool from Chrome Dev Tools.
Then timeline-chart can be obtained by changing `Heavy(Bottom Up)` option to `Chart`.

**Comment by smetj** [comment]
Yeah that's it. Thanks the tip!
